### ISSUE TITLE
A quick note on using gif_load

### ISSUE THREAD

**Issue by hidefromkgb** [takeiteasy/meh#1]
Hi, this is `gif_load` tech support ^__^
I\`d like to clarify a couple of important things.
1. Each frame in a GIF might have its own delay, so storing frame delay in a single value isn\`t going to work as expected; they should rather be stored in an array (C-like one, `NSArray`, `CFArrayRef` — whichever you prefer).
1. `memcpy`-ing the frame to persistent storage should take place before filling it with the background color; if it so happens that the current frame has `GIF_BKGD` blending mode ('restore background' mode in terms of the GIF89a standard), you\`ll be left with a frame filled with background color instead of what it should actually contain.
1. There is a frame blending mode I called `GIF_PREV` that is extremely rare in the wild and cannot even be created with Photoshop or GIMP, which commands the loader to restore the previous frame. However, just in case you want to fully comply with the standard, please add a `memcpy` from the previous frame to `pict` if `(whdr->mode == GIF_PREV)` after you\`ve finished creating the current one.

BTW thanks for using my lib!

**Comment by takeiteasy** [comment]
Thanks for the advice, and taking the time to give it. I'll look into some of these when I get some time. I don't work on this that often.

Also thanks for making the lib, it's very nice.
